version: '3'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1
  node-server:
    build: ./node-server
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./node-server/cache:/weavedb/cache
    depends_on:
      - cache    
  envoy:
    build: ./envoy
    ports:
      - "8080:8080"
    links:
      - node-server
