version: '3'
services:
  node-server:
    build: ./node-server
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./node-server/cache:/node-server/cache
  envoy:
    build: ./envoy
    ports:
      - "8080:8080"
    links:
      - node-server
